config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resource :help do
    get :oauth2
  end

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status, to: 'projects#badge'
      get :integration
      post :build
      post :toggle_shared_runners
    end

    resources :services, only: [:index, :edit, :update] do
      member do
        get :test
      end
    end

    resource :charts, only: [:show]

    resources :refs, constraints: { ref_id: /.*/ }, only: [] do
      resources :commits, only: [:show] do
        member do
          get :status
        end
      end
    end

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :web_hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end

    resources :runners, only: [:index, :edit, :update, :destroy, :show] do
      member do
        get :resume
        get :pause
      end
    end

    resources :runner_projects, only: [:create, :destroy]

    resources :jobs, only: [:index] do
      collection do
        get :deploy_jobs
      end
    end

    resources :events, only: [:index]
  end

  resource :user_sessions do
    get :auth
    get :callback
  end

  namespace :admin do
    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        put :assign_all
        get :resume
        get :pause
      end
    end

    resources :events, only: [:index]

    resources :projects do
      resources :runner_projects
    end

    resources :builds, only: :index
  end

  root to: 'projects#index'
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id             :integer          not null, primary key
#  project_id     :integer          not null
#  commands       :text
#  active         :boolean          default(TRUE), not null
#  created_at     :datetime
#  updated_at     :datetime
#  name           :string(255)
#  build_branches :boolean          default(TRUE), not null
#  build_tags     :boolean          default(FALSE), not null
#  job_type       :string(255)      default("parallel")
#  refs           :string(255)
#  deleted_at     :datetime
#

class Job < ActiveRecord::Base
  acts_as_paranoid
  
  belongs_to :project
  has_many :builds

  acts_as_taggable

  scope :active, ->() { where(active: true) }
  scope :archived, ->() { where(active: false) }
  scope :parallel, ->(){ where(job_type: "parallel") }
  scope :deploy, ->(){ where(job_type: "deploy") }

  validate :refs, length: { maximum: 255 }

  def deploy?
    job_type == "deploy"
  end

  def run_for_ref?(ref)
    if refs.present?
      refs.split(",").map(&:strip).each do |refs_val|
        return true if File.fnmatch(refs_val, ref)
      end

      false
    else
      true
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :project
  before_filter :authorize_access_project!
  before_filter :authorize_manage_project!

  layout 'project'

  def index
  end

  def deploy_jobs
  end

  private

  def project
    @project ||= Project.find(params[:project_id])
  end
end

app/views/jobs/_deploy_job_edit.html.haml
= nested_form_for @project, html: { class: 'form-horizontal' } do |f|
  - if @project.errors.any?
    #error_explanation
      %p.lead= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      .alert.alert-error
        %ul
          - @project.errors.full_messages.each do |msg|
            %li= msg

  = f.fields_for :jobs do |job_form|
    - if job_form.object.job_type == "deploy" || job_form.object.new_record?

      = job_form.hidden_field :job_type, value: "deploy"
      .form-group
        = job_form.label :name, 'Name', class: 'control-label'
        .col-sm-10
          = job_form.text_field :name, class: 'form-control', placeholder: "Staging"
      .form-group
        = job_form.label :tag_list, class: 'control-label' do
          Tags
        .col-sm-10
          = job_form.text_field :tag_list, class: 'form-control'
          .help-block
            This job will only use runners that contain all these tags.
            Leave blank if you want this job to use any runner

      .form-group
        = job_form.label :refs, class: 'control-label' do
          Refs
        .col-sm-10
          = job_form.text_field :refs, class: 'form-control', placeholder: "master, staging, feature/*, tags/testing*"
          .help-block
            Run only when the above git refs strings match the branch or tag that was pushed.
            %br
            Accepts strings and glob pattern syntax

      .form-group
        = job_form.label :commands, 'Script', class: 'control-label'
        .col-sm-10
          = job_form.text_area :commands, class: 'form-control', rows: 10, placeholder: "bundle exec rake spec"
          %p.light
            All lines will be concatenated into one file and executed.
            %br
            If you change the working directory or the environment this will affect all following lines.
            %br
            = link_to("Example job scripts", "https://gitlab.com/gitlab-org/gitlab-ci/tree/master/doc/examples")
          = job_form.link_to_remove "Remove this job", class: 'btn btn-danger pull-right'
      %hr
  .clearfix
    = f.link_to_add "Add a job", :jobs, class: 'btn btn-save pull-right'

  .form-actions
    = f.submit 'Save changes', class: 'btn btn-success'

app/views/jobs/_edit.html.haml
= nested_form_for @project, html: { class: 'form-horizontal' } do |f|
  - if @project.errors.any?
    #error_explanation
      %p.lead= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      .alert.alert-error
        %ul
          - @project.errors.full_messages.each do |msg|
            %li= msg

  = f.fields_for :jobs do |job_form|
    - if job_form.object.job_type == "parallel" || job_form.object.new_record?
      .form-group
        = job_form.label :name, 'Name', class: 'control-label'
        .col-sm-10
          = job_form.text_field :name, class: 'form-control', placeholder: "Ex. cucumber"
      .form-group
        = job_form.label :build_branches, 'Trigger', class: 'control-label'
        .col-sm-10
          .checkbox
            = job_form.label :build_branches, 'Builds commits', class: ''
            = job_form.check_box :build_branches
          .checkbox
            = job_form.label :build_tags, 'Build tags', class: ''
            = job_form.check_box :build_tags
      .form-group
        = job_form.label :tag_list, class: 'control-label' do
          Tags
        .col-sm-10
          = job_form.text_field :tag_list, class: 'form-control'
          .help-block
            This job will only use runners that contain all these tags.
            Leave blank if you want this job to use any runner

      .form-group
        = job_form.label :commands, 'Script', class: 'control-label'
        .col-sm-10
          = job_form.text_area :commands, class: 'form-control', rows: 10, placeholder: "bundle exec rake spec"
          %p.light
            All lines will be concatenated into one file and executed.
            %br
            If you change the working directory or the environment this will affect all following lines.
            %br
            = link_to("Example job scripts", "https://gitlab.com/gitlab-org/gitlab-ci/tree/master/doc/examples")
          = job_form.link_to_remove "Remove this job", class: 'btn btn-danger pull-right'
      %hr
  .clearfix
    = f.link_to_add "Add a job", :jobs, class: 'btn btn-save pull-right'

  .form-actions
    = f.submit 'Save changes', class: 'btn btn-success'

app/views/jobs/_list.html.haml
%table.table
  %thead
    %tr
      %th Name
      %th Build commits
      %th Build tags
      %th Tags

  %tbody
    - @project.jobs.each do |job|
      %tr
        %td= job.name
        %td= check_box_tag nil, nil, job.build_branches, disabled: true
        %td= check_box_tag nil, nil, job.build_tags, disabled: true
        %td
          - job.tag_list.each do |tag|
            %span.label.label-primary
              = tag

app/views/jobs/deploy_jobs.html.haml
%ul.nav.nav-tabs.append-bottom-20
  %li
    = link_to 'Test (run in parallel)', project_jobs_path(@project)
  %li{class: "active"}
    = link_to 'Deploy (run on success)', deploy_jobs_project_jobs_path(@project)
 

%p.slead
  Deploy jobs are scripts you want CI to run on succeeding all parallel builds


= render 'deploy_job_edit'

app/views/jobs/index.html.haml
%ul.nav.nav-tabs.append-bottom-20
  %li{class: "active"}
    = link_to 'Test (run in parallel)', project_jobs_path(@project)
  %li
    = link_to 'Deploy (run on success)', deploy_jobs_project_jobs_path(@project)
  
  

.btn-group.pull-right
  = link_to project_jobs_path(@project), class: "btn #{'active' unless params[:list]}" do
    %i.icon-edit
    Edit
  = link_to project_jobs_path(@project, list: 'true'), class: "btn #{'active' if params[:list]}" do
    %i.icon-list
    List
%p.slead
  Jobs are scripts you want CI to run on each push to repository

%hr

- if params[:list]
  = render 'list'
- else
  = render 'edit'