config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resource :help do
    get :oauth2
  end

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status, to: 'projects#badge'
      get :integration
      post :build
      post :toggle_shared_runners
    end

    resources :services, only: [:index, :edit, :update] do
      member do
        get :test
      end
    end

    resource :charts, only: [:show]

    resources :refs, constraints: { ref_id: /.*/ }, only: [] do
      resources :commits, only: [:show] do
        member do
          get :status
        end
      end
    end

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :web_hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end

    resources :runners, only: [:index, :edit, :update, :destroy, :show] do
      member do
        get :resume
        get :pause
      end
    end

    resources :runner_projects, only: [:create, :destroy]

    resources :jobs, only: [:index] do
      collection do
        get :deploy_jobs
      end
    end

    resources :events, only: [:index]
  end

  resource :user_sessions do
    get :auth
    get :callback
  end

  namespace :admin do
    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        put :assign_all
        get :resume
        get :pause
      end
    end

    resources :events, only: [:index]

    resources :projects do
      resources :runner_projects
    end

    resources :builds, only: :index
  end

  root to: 'projects#index'
end

app/views/shared/_guide.html.haml
.bs-callout.help-callout
  %h4 How to setup CI for this project

  %ol
    %li
      Add at least one runner to the project.
      Go to #{link_to 'Runners page', project_runners_path(@project), target: :blank} for instructions.
    %li
      Setup at least one Job with a build script.
      Go to #{link_to 'Jobs page', project_jobs_path(@project), target: :blank} for instructions.
    %li
      Visit #{link_to 'GitLab project settings', @project.gitlab_url + "/services/gitlab_ci/edit", target: :blank}
      and press the "Test settings" button.
    %li
      Return to this page and refresh it, it should show a new build.

app/views/shared/_no_runners.html.haml
.alert.alert-danger
  %p
    Now you need Runners to process your builds.
  %span
    Checkout the #{link_to 'GitLab Runner section', 'https://about.gitlab.com/gitlab-ci/#gitlab-runner', target: '_blank'} to install it